### ISSUE TITLE
Feature flaw: createtut

### ISSUE THREAD

**Issue by gladwintan** [AY2425S1-CS2103T-W08-2/tp#195]
Should we block inputs that are greater than a certain length? It's unlikely tutorials names would be very long

**Comment by jinhanjinhan** [comment]
hmmm yea i was thinking about this as well. Right now the only constraint for tutorial is that the string must be alphanumeric, so what other restrictions should we impose for tutorials?

**Comment by jinhanjinhan** [comment]
I think cannot change this anymore lol
