### ISSUE TITLE
Feature flaw: Edit command pay prefix usage not very intuitive for users

### ISSUE THREAD

**Issue by jinhanjinhan** [AY2425S1-CS2103T-W08-2/tp#207]
<img width="997" alt="Screenshot 2024-10-30 at 5 01 55 PM" src="https://github.com/user-attachments/assets/38a9f3c0-e4ef-4a62-a15e-a18927328936">
When doing "edit 1 pay/2000", it shows the payment overdue to be 2000, I think it should be paid 2000 instead, so the advance portion should display 2000.

**Comment by Slipperybara** [comment]
This issue has been resolved
