### ISSUE TITLE
Feature flaw: Markpaid command should check for integer overflow

### ISSUE THREAD

**Issue by jinhanjinhan** [AY2425S1-CS2103T-W08-2/tp#208]
<img width="997" alt="Screenshot 2024-10-30 at 5 07 15 PM" src="https://github.com/user-attachments/assets/8466a324-261d-41e1-a73d-913f8445657a">
I think markpaid should check for integer overflow here, if not the program will just freeze.

**Comment by Slipperybara** [comment]
Will move this to planned enhancements
