### ISSUE TITLE
UI Suggestion: UI does not update promptly

### ISSUE THREAD

**Issue by jinhanjinhan** [AY2425S1-CS2103T-W08-2/tp#209]
<img width="997" alt="Screenshot 2024-10-30 at 5 22 38 PM" src="https://github.com/user-attachments/assets/1f027ee1-75f3-4ef9-857d-da38568cceb4">
When doing "enroll 1 tut/m", the UI updates to enroll student 1 to tutotrial named m, but when doing "enroll 3 tut/m", the UI does not update promptly. Is there a fix for this? if it is too hard, then it is fine.

**Comment by gladwintan** [comment]
I ran enroll 1 and enroll 3, and the UI did update to show the tutorial. What commands did you run?
