### ISSUE TITLE
Feature flaw: Return message not clear for unenroll command

### ISSUE THREAD

**Issue by jinhanjinhan** [AY2425S1-CS2103T-W08-2/tp#210]
<img width="997" alt="Screenshot 2024-10-30 at 5 25 23 PM" src="https://github.com/user-attachments/assets/50835b71-733d-4867-b390-5f2f2587201e">
When doing "unenroll 2 tut/m", the error message is this person is not enrolled in this tutorial. Maybe can say something like "Cannot unenroll {STUDENT_NAME} from {TUTORIAL_NAME} as he/she is currently not enrolled in {TUTORIAL_NAME}"

**Comment by Slipperybara** [comment]
alright will do that
