### ISSUE TITLE
Feature flaw: Edit command and add command case sensitivity issues for name

### ISSUE THREAD

**Issue by jinhanjinhan** [AY2425S1-CS2103T-W08-2/tp#211]
<img width="995" alt="Screenshot 2024-10-30 at 5 33 21 PM" src="https://github.com/user-attachments/assets/72940a05-fb1a-42f0-8cbd-611053c82157">
When I tried to edit another person's name and phone number to that of another name in the address book, it works as the checking of names is case-sensitive, so different casing are considered different names, but according to the textbook, the case for names in real-world context should be case-insensitive, so when checking for duplicate person, we should use equalsIgnoreCase() to check. 

Same for add command as well

**Comment by Slipperybara** [comment]
This issue has been fixed
