### ISSUE TITLE
Documentation Bug: UG not updated for attend commands

### ISSUE THREAD

**Issue by amitha2210** [AY2425S1-CS2103T-W08-2/tp#216]
The UG is not updated with the new commands "mas", "umas" and "mat", still uses the old markattend command.

![Screenshot 2024-10-31 at 5 41 53 PM](https://github.com/user-attachments/assets/c7b1bd8e-81f0-4300-a6d5-f1529fa3b15b)

**Comment by Slipperybara** [comment]
This issue has been fixed
