### ISSUE TITLE
UI suggestion: Tutorial does not update promptly

### ISSUE THREAD

**Issue by amitha2210** [AY2425S1-CS2103T-W08-2/tp#221]
The tutorial only appears for the student after the markpaid command has been used to mark the payment of the student, until then tutorial section remains empty.

<img width="844" alt="Screenshot 2024-10-31 at 11 36 50 PM" src="https://github.com/user-attachments/assets/6e87d69c-58d1-4ce0-b06c-4975984f6329">

**Comment by Slipperybara** [comment]
Think this issue have been fixed
