### ISSUE TITLE
Feature suggestion: date shown for attendance

### ISSUE THREAD

**Issue by amitha2210** [AY2425S1-CS2103T-W08-2/tp#223]
If the user marks the student as attended for a second time for the same week, but on a different day, only the old date for attendance is shown, despite a new attendance object being created. Maybe we could check for whether the attendance created is made for a date within the same week, then show the user a message to double check whether it is the correct date?

<img width="811" alt="Screenshot 2024-10-31 at 11 45 22 PM" src="https://github.com/user-attachments/assets/2aea8672-2237-4892-a918-e14dd362f8ba">

**Comment by Slipperybara** [comment]
Good suggestion, but I think we could consider this as a future implementation, I will move this to future implementation
