### ISSUE TITLE
Feature flaw: Finding by address matches any substring 

### ISSUE THREAD

**Issue by gladwintan** [AY2425S1-CS2103T-W08-2/tp#284]
Command: find a/Blk 30 geylang

Returns all students with "Blk" in their address even though the user might want a narrowed search

**Comment by jinhanjinhan** [comment]
Yep indeed, because for find, multiple word search is connected by an OR clause. So even `find n/David Li` will show results of a person named david li and another person named charlotte linette. I think jerry will update this as a planned enhancement for the feature

**Comment by jinhanjinhan** [comment]
Okay I think this is included as one of the planned enhancements already
