### ISSUE TITLE
[PE-D][Tester B] addfees: Integer overflow when accumulating a lot of fees

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W08-2/tp#324]
When `addfees` is run multiple times with large amounts, the total amount may overflow to become advance.

Steps to reproduce:
1. Create a tutorial, `createtut tut/Math`
2. Enroll a student to the tutorial, `enroll 1 tut/Math`
3. Add fees for the student repeatedly, `addfees 1 pay/999999999`

![Amount overdue is negative and student now has advance payment](https://raw.githubusercontent.com/joeltio/ped/main/files/11a487d0-8e37-4286-97fd-0f5a06850eb6.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: joeltio/ped#4

**Comment by Slipperybara** [comment]
NotInScope
