### ISSUE TITLE
[PE-D][Tester D]  Grammar Errors in Section 5.3 of the User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W08-2/tp#341]
![image.png](https://raw.githubusercontent.com/meerkatboy/ped/main/files/da16c831-a6da-456d-8ddc-f0b64b800d0f.png)

Similar error as before, can be taken note of.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: meerkatboy/ped#7

**Comment by Slipperybara** [comment]
should be has paid

**Comment by Slipperybara** [comment]
done
